import { MarkdownEditor } from "@/components/markdown-editor";
import { UploadField } from "@/components/upload-field";
import { requireAdmin } from "@/lib/admin";
import { getArticles, getCategories } from "@/lib/data";
import { deleteArticle, saveArticle } from "@/app/actions";

function ArticleFields({ article, categories }: { article?: Awaited<ReturnType<typeof getArticles>>[number]; categories: Awaited<ReturnType<typeof getCategories>> }) {
  return <form action={saveArticle} className="admin-form"><input type="hidden" name="id" value={article?.id ?? ""} /><div className="form-grid"><label>Title<input name="title" defaultValue={article?.title} required /></label><label>URL slug<input name="slug" defaultValue={article?.slug} placeholder="generated-from-title" /></label><label className="full-field">Excerpt<textarea name="excerpt" defaultValue={article?.excerpt} rows={2} required /></label><label>Category<select name="categoryId" defaultValue={article?.categoryId ?? categories[0]?.id} required disabled={categories.length === 0}>{categories.map((category) => <option value={category.id} key={category.id}>{category.name}</option>)}</select>{categories.length === 0 && <small>Create a category before saving an article.</small>}</label><label>Status<select name="status" defaultValue={article?.status ?? "DRAFT"}><option value="DRAFT">Draft</option><option value="PUBLISHED">Published</option></select></label><label className="full-field">Tags <small>comma separated</small><input name="tags" defaultValue={article?.tags.join(", ")} placeholder="backend, systems" /></label><div className="full-field"><UploadField name="coverImage" kind="article" label="Cover image" initialUrl={article?.coverImage ?? ""} /></div><label className="full-field">Article content<MarkdownEditor initialValue={article?.content ?? ""} /></label></div><div className="form-actions"><span>Reading time is calculated automatically.</span><button className="admin-button primary" type="submit" disabled={categories.length === 0}>{article ? "save article" : "create article"} ↗</button></div></form>;
}

export default async function ArticlesManager({ searchParams }: { searchParams: Promise<{ error?: string; saved?: string }> }) {
  await requireAdmin(); const [articles, categories, params] = await Promise.all([getArticles(true), getCategories(), searchParams]);
  return <div className="admin-page"><div className="admin-page-heading"><div><p className="eyebrow">publishing</p><h1>Articles</h1><p>Draft ideas, polish your Markdown, and publish when ready.</p></div></div>{params.error && <p className="admin-alert">{params.error}</p>}{params.saved && <p className="admin-success">Article changes saved.</p>}<section className="admin-panel"><div className="admin-panel-heading"><h2>New article</h2><span>MARKDOWN SUPPORTED</span></div><ArticleFields categories={categories} /></section><section className="admin-panel admin-list-panel"><div className="admin-panel-heading"><h2>Existing articles <span className="count-badge">{articles.length}</span></h2></div>{articles.map((article) => <details className="managed-item" key={article.id}><summary><span><strong>{article.title}</strong><small>{article.status} · {article.category?.name ?? "uncategorized"}</small></span><span className={`status-label ${article.status.toLowerCase()}`}>{article.status}</span></summary><ArticleFields article={article} categories={categories} /><form action={deleteArticle} className="delete-form"><input type="hidden" name="id" value={article.id} /><button type="submit">delete article</button></form></details>)}</section></div>;
}